cmake_minimum_required(VERSION 3.15)

project(zserio_data_view_approaches)

add_subdirectory(runtime/src)

add_subdirectory(src/approach_0_current)
add_subdirectory(src/approach_1_namespace)
add_subdirectory(src/approach_2_using)
add_subdirectory(src/approach_3_top_namespace)
add_subdirectory(src/approach_4_top_view)
add_subdirectory(src/approach_5_global_data_view)
