/**
 * Automatically generated by Zserio C++17 generator version 0.5.0 using Zserio core 2.17.0.
 * Generator setup: stdAllocator.
 */

#ifndef NDS_VIEW_STRUCT_TEMPLATED_FIELD_COMPOUND_H
#define NDS_VIEW_STRUCT_TEMPLATED_FIELD_COMPOUND_H

#include <nds/data/struct_templated_field/Compound.h>

#include <zserio/View.h>

namespace zserio
{

template <>
class View<::nds::data::struct_templated_field::Compound>
{
public:
    explicit View(const ::nds::data::struct_templated_field::Compound& data) noexcept;

    ::zserio::UInt32 value() const;

    const ::nds::data::struct_templated_field::Compound& zserioData() const;

protected:
    View(const ::nds::data::struct_templated_field::Compound& data, const View& other) noexcept;

private:
    const ::nds::data::struct_templated_field::Compound* m_data;
};

bool operator==(const View<::nds::data::struct_templated_field::Compound>& lhs, const View<::nds::data::struct_templated_field::Compound>& rhs);
bool operator<(const View<::nds::data::struct_templated_field::Compound>& lhs, const View<::nds::data::struct_templated_field::Compound>& rhs);
bool operator!=(const View<::nds::data::struct_templated_field::Compound>& lhs, const View<::nds::data::struct_templated_field::Compound>& rhs);
bool operator>(const View<::nds::data::struct_templated_field::Compound>& lhs, const View<::nds::data::struct_templated_field::Compound>& rhs);
bool operator<=(const View<::nds::data::struct_templated_field::Compound>& lhs, const View<::nds::data::struct_templated_field::Compound>& rhs);
bool operator>=(const View<::nds::data::struct_templated_field::Compound>& lhs, const View<::nds::data::struct_templated_field::Compound>& rhs);

namespace detail
{

template <>
struct ObjectTraits<::nds::data::struct_templated_field::Compound>
{
    static void validate(const View<::nds::data::struct_templated_field::Compound>& view, ::std::string_view fieldName);

    static BitSize bitSizeOf(const View<::nds::data::struct_templated_field::Compound>& view, BitSize bitPosition);

    static void write(BitStreamWriter& writer, const View<::nds::data::struct_templated_field::Compound>& view);

    static View<::nds::data::struct_templated_field::Compound> read(BitStreamReader& reader, ::nds::data::struct_templated_field::Compound& data);
};

} // namespace detail

} // namespace zserio

namespace nds::view::struct_templated_field
{

using Compound = ::zserio::View<::nds::data::struct_templated_field::Compound>;

} // namespace nds::view::struct_templated_field

namespace std
{

template <>
struct hash<::zserio::View<::nds::data::struct_templated_field::Compound>>
{
    size_t operator()(const ::zserio::View<::nds::data::struct_templated_field::Compound>& view) const;
};

} // namespace std

#endif // NDS_VIEW_STRUCT_TEMPLATED_FIELD_COMPOUND_H
