/**
 * Automatically generated by Zserio C++17 generator version 0.5.0 using Zserio core 2.17.0.
 * Generator setup: stdAllocator.
 */

#include <zserio/BitPositionUtil.h>
#include <zserio/BitStreamReader.h>
#include <zserio/BitStreamWriter.h>
#include <zserio/HashCodeUtil.h>

#include "Compound.h"

namespace zserio
{

View<::nds::data::struct_templated_field::Compound>::View(const ::nds::data::struct_templated_field::Compound& data) noexcept :
        m_data(&data)
{}

View<::nds::data::struct_templated_field::Compound>::View(const ::nds::data::struct_templated_field::Compound& data,
        const View&) noexcept :
        m_data(&data)
{}

::zserio::UInt32 View<::nds::data::struct_templated_field::Compound>::value() const
{
    return m_data->value;
}

const ::nds::data::struct_templated_field::Compound& View<::nds::data::struct_templated_field::Compound>::zserioData() const
{
    return *m_data;
}

bool operator==(const View<::nds::data::struct_templated_field::Compound>& lhs, const View<::nds::data::struct_templated_field::Compound>& rhs)
{
    return lhs.value() == rhs.value();
}

bool operator<(const View<::nds::data::struct_templated_field::Compound>& lhs, const View<::nds::data::struct_templated_field::Compound>& rhs)
{
    if (lhs.value() != rhs.value())
    {
        return lhs.value() < rhs.value();
    }

    return false;
}

bool operator!=(const View<::nds::data::struct_templated_field::Compound>& lhs, const View<::nds::data::struct_templated_field::Compound>& rhs)
{
    return !(lhs == rhs);
}

bool operator>(const View<::nds::data::struct_templated_field::Compound>& lhs, const View<::nds::data::struct_templated_field::Compound>& rhs)
{
    return rhs < lhs;
}

bool operator<=(const View<::nds::data::struct_templated_field::Compound>& lhs, const View<::nds::data::struct_templated_field::Compound>& rhs)
{
    return !(rhs < lhs);
}

bool operator>=(const View<::nds::data::struct_templated_field::Compound>& lhs, const View<::nds::data::struct_templated_field::Compound>& rhs)
{
    return !(lhs < rhs);
}

namespace detail
{

void ObjectTraits<::nds::data::struct_templated_field::Compound>::validate(const View<::nds::data::struct_templated_field::Compound>& view, ::std::string_view)
{
    detail::validate(view.value(), "'Compound.value'");
}

BitSize ObjectTraits<::nds::data::struct_templated_field::Compound>::bitSizeOf(const View<::nds::data::struct_templated_field::Compound>& view, BitSize bitPosition)
{
    BitSize endBitPosition = bitPosition;

    auto value_ = view.value();
    endBitPosition += detail::bitSizeOf(value_, endBitPosition);

    return endBitPosition - bitPosition;
}

void ObjectTraits<::nds::data::struct_templated_field::Compound>::write(BitStreamWriter& writer, const View<::nds::data::struct_templated_field::Compound>& view)
{
    auto value_ = view.value();
    detail::write(writer, value_);
}

View<::nds::data::struct_templated_field::Compound> ObjectTraits<::nds::data::struct_templated_field::Compound>::read(BitStreamReader& reader, ::nds::data::struct_templated_field::Compound& data)
{
    View<::nds::data::struct_templated_field::Compound> view(data);
    detail::read(reader, data.value);
    return view;
}

} // namespace detail
} // namespace zserio

namespace std
{

size_t hash<::zserio::View<::nds::data::struct_templated_field::Compound>>::operator()(const ::zserio::View<::nds::data::struct_templated_field::Compound>& view) const
{
    uint32_t result = ::zserio::HASH_SEED;
    result = ::zserio::calcHashCode(result, view.value());
    return static_cast<size_t>(result);
}

} // namespace std
