/**
 * Automatically generated by Zserio C++17 generator version 0.5.0 using Zserio core 2.17.0.
 * Generator setup: stdAllocator.
 */

#ifndef NDS_VIEW_STRUCT_TEMPLATED_FIELD_FIELD_H
#define NDS_VIEW_STRUCT_TEMPLATED_FIELD_FIELD_H

#include <nds/data/struct_templated_field/Field.h>

#include <zserio/View.h>
#include <zserio/ArrayView.h>

namespace zserio
{

template <typename T>
class View<::nds::data::struct_templated_field::Field<T>>
{
public:
    explicit View(const ::nds::data::struct_templated_field::Field<T>& data) noexcept:
            m_data(&data)
    {}

    view_type_t<T> value() const
    {
        if constexpr (detail::is_view_v<view_type_t<T>>)
        {
            return view_type_t<T>(m_data->value);
        }
        else
        {
            return m_data->value;
        }
    }

    ArrayView<const T> arr() const
    {
        return ArrayView<const T>(m_data->arr);
    }

    const ::nds::data::struct_templated_field::Field<T>& zserioData() const;

protected:
    View(const ::nds::data::struct_templated_field::Field<T>& data, const View&) noexcept :
            m_data(&data)
    {}

private:
    const ::nds::data::struct_templated_field::Field<T>* m_data;
};

template <typename T>
bool operator==(const View<::nds::data::struct_templated_field::Field<T>>& lhs, const View<::nds::data::struct_templated_field::Field<T>>& rhs)
{
    return lhs.value() == rhs.value() &&
            lhs.arr() == rhs.arr();
}

template <typename T>
bool operator<(const View<::nds::data::struct_templated_field::Field<T>>& lhs, const View<::nds::data::struct_templated_field::Field<T>>& rhs)
{
    if (lhs.value() != rhs.value())
    {
        return lhs.value() < rhs.value();
    }
    if (lhs.arr() != rhs.arr())
    {
        return lhs.arr() < rhs.arr();
    }

    return false;
}

template <typename T>
bool operator!=(const View<::nds::data::struct_templated_field::Field<T>>& lhs, const View<::nds::data::struct_templated_field::Field<T>>& rhs)
{
    return !(lhs == rhs);
}

template <typename T>
bool operator>(const View<::nds::data::struct_templated_field::Field<T>>& lhs, const View<::nds::data::struct_templated_field::Field<T>>& rhs)
{
    return rhs < lhs;
}

template <typename T>
bool operator<=(const View<::nds::data::struct_templated_field::Field<T>>& lhs, const View<::nds::data::struct_templated_field::Field<T>>& rhs)
{
    return !(rhs < lhs);
}

template <typename T>
bool operator>=(const View<::nds::data::struct_templated_field::Field<T>>& lhs, const View<::nds::data::struct_templated_field::Field<T>>& rhs)
{
    return !(lhs < rhs);
}

namespace detail
{

template <typename T>
struct ObjectTraits<::nds::data::struct_templated_field::Field<T>>
{
    static void validate(const View<::nds::data::struct_templated_field::Field<T>>& view, ::std::string_view)
    {
        detail::validate(view.value(), "'Field.value'");
        detail::validate<ArrayType::NORMAL>(view.arr(), "'Field.arr'", static_cast<size_t>(3));
    }

    static BitSize bitSizeOf(const View<::nds::data::struct_templated_field::Field<T>>& view, BitSize bitPosition)
    {
        BitSize endBitPosition = bitPosition;

        auto value_ = view.value();
        endBitPosition += detail::bitSizeOf(value_, endBitPosition);
        auto arr_ = view.arr();
        endBitPosition += detail::bitSizeOf<ArrayType::NORMAL>(arr_, endBitPosition);

        return endBitPosition - bitPosition;
    }

    static void write(BitStreamWriter& writer, const View<::nds::data::struct_templated_field::Field<T>>& view)
    {
        auto value_ = view.value();
        detail::write(writer, value_);
        auto arr_ = view.arr();
        detail::write<ArrayType::NORMAL>(writer, arr_);
    }

    static View<::nds::data::struct_templated_field::Field<T>> read(BitStreamReader& reader, ::nds::data::struct_templated_field::Field<T>& data)
    {
        View<::nds::data::struct_templated_field::Field<T>> view(data);
        detail::read(reader, data.value);
        detail::read<ArrayType::NORMAL>(reader, data.arr, static_cast<size_t>(3));
        return view;
    }
};

} // namespace detail
} // namespace zserio

namespace nds::view::struct_templated_field
{

template <typename T>
using Field = ::zserio::View<nds::data::struct_templated_field::Field<T>>;

} // namespace nds::view::struct_templated_field

namespace std
{

template <typename T>
struct hash<::zserio::View<::nds::data::struct_templated_field::Field<T>>>
{
    size_t operator()(const ::zserio::View<::nds::data::struct_templated_field::Field<T>>& view) const
    {
        uint32_t result = ::zserio::HASH_SEED;
        result = ::zserio::calcHashCode(result, view.value());
        result = ::zserio::calcHashCode(result, view.arr());
        return static_cast<size_t>(result);
    }
};

} // namespace std

#endif // NDS_VIEW_STRUCT_TEMPLATED_FIELD_FIELD_H
