/**
 * Automatically generated by Zserio C++17 generator version 0.5.0 using Zserio core 2.17.0.
 * Generator setup: stdAllocator.
 */

#include <zserio/BitPositionUtil.h>
#include <zserio/BitStreamReader.h>
#include <zserio/BitStreamWriter.h>
#include <zserio/HashCodeUtil.h>

#include "StructTemplatedField.h"

namespace zserio
{

View<::nds::data::struct_templated_field::StructTemplatedField>::View(const ::nds::data::struct_templated_field::StructTemplatedField& data) noexcept :
        m_data(&data)
{}

View<::nds::data::struct_templated_field::StructTemplatedField>::View(const ::nds::data::struct_templated_field::StructTemplatedField& data,
        const View&) noexcept :
        m_data(&data)
{}

::zserio::View<::nds::data::struct_templated_field::Field<::zserio::UInt32>> View<::nds::data::struct_templated_field::StructTemplatedField>::uint32Field() const
{
    return ::zserio::View<::nds::data::struct_templated_field::Field<::zserio::UInt32>>(m_data->uint32Field);
}

::zserio::View<::nds::data::struct_templated_field::Field<::nds::data::struct_templated_field::Compound>> View<::nds::data::struct_templated_field::StructTemplatedField>::compoundField() const
{
    return ::zserio::View<::nds::data::struct_templated_field::Field<::nds::data::struct_templated_field::Compound>>(m_data->compoundField);
}

::zserio::View<::nds::data::struct_templated_field::Field<::zserio::String>> View<::nds::data::struct_templated_field::StructTemplatedField>::stringField() const
{
    return ::zserio::View<::nds::data::struct_templated_field::Field<::zserio::String>>(m_data->stringField);
}

const ::nds::data::struct_templated_field::StructTemplatedField& View<::nds::data::struct_templated_field::StructTemplatedField>::zserioData() const
{
    return *m_data;
}

bool operator==(const View<::nds::data::struct_templated_field::StructTemplatedField>& lhs, const View<::nds::data::struct_templated_field::StructTemplatedField>& rhs)
{
    return lhs.uint32Field() == rhs.uint32Field() &&
            lhs.compoundField() == rhs.compoundField() &&
            lhs.stringField() == rhs.stringField();
}

bool operator<(const View<::nds::data::struct_templated_field::StructTemplatedField>& lhs, const View<::nds::data::struct_templated_field::StructTemplatedField>& rhs)
{
    if (lhs.uint32Field() != rhs.uint32Field())
    {
        return lhs.uint32Field() < rhs.uint32Field();
    }
    if (lhs.compoundField() != rhs.compoundField())
    {
        return lhs.compoundField() < rhs.compoundField();
    }
    if (lhs.stringField() != rhs.stringField())
    {
        return lhs.stringField() < rhs.stringField();
    }

    return false;
}

bool operator!=(const View<::nds::data::struct_templated_field::StructTemplatedField>& lhs, const View<::nds::data::struct_templated_field::StructTemplatedField>& rhs)
{
    return !(lhs == rhs);
}

bool operator>(const View<::nds::data::struct_templated_field::StructTemplatedField>& lhs, const View<::nds::data::struct_templated_field::StructTemplatedField>& rhs)
{
    return rhs < lhs;
}

bool operator<=(const View<::nds::data::struct_templated_field::StructTemplatedField>& lhs, const View<::nds::data::struct_templated_field::StructTemplatedField>& rhs)
{
    return !(rhs < lhs);
}

bool operator>=(const View<::nds::data::struct_templated_field::StructTemplatedField>& lhs, const View<::nds::data::struct_templated_field::StructTemplatedField>& rhs)
{
    return !(lhs < rhs);
}

namespace detail
{

void ObjectTraits<::nds::data::struct_templated_field::StructTemplatedField>::validate(const View<::nds::data::struct_templated_field::StructTemplatedField>& view, ::std::string_view)
{
    detail::validate(view.uint32Field(), "'StructTemplatedField.uint32Field'");
    detail::validate(view.compoundField(), "'StructTemplatedField.compoundField'");
    detail::validate(view.stringField(), "'StructTemplatedField.stringField'");
}

BitSize ObjectTraits<::nds::data::struct_templated_field::StructTemplatedField>::bitSizeOf(const View<::nds::data::struct_templated_field::StructTemplatedField>& view, BitSize bitPosition)
{
    BitSize endBitPosition = bitPosition;

    auto uint32Field_ = view.uint32Field();
    endBitPosition += detail::bitSizeOf(uint32Field_, endBitPosition);
    auto compoundField_ = view.compoundField();
    endBitPosition += detail::bitSizeOf(compoundField_, endBitPosition);
    auto stringField_ = view.stringField();
    endBitPosition += detail::bitSizeOf(stringField_, endBitPosition);

    return endBitPosition - bitPosition;
}

void ObjectTraits<::nds::data::struct_templated_field::StructTemplatedField>::write(BitStreamWriter& writer, const View<::nds::data::struct_templated_field::StructTemplatedField>& view)
{
    auto uint32Field_ = view.uint32Field();
    detail::write(writer, uint32Field_);
    auto compoundField_ = view.compoundField();
    detail::write(writer, compoundField_);
    auto stringField_ = view.stringField();
    detail::write(writer, stringField_);
}

View<::nds::data::struct_templated_field::StructTemplatedField> ObjectTraits<::nds::data::struct_templated_field::StructTemplatedField>::read(BitStreamReader& reader, ::nds::data::struct_templated_field::StructTemplatedField& data)
{
    View<::nds::data::struct_templated_field::StructTemplatedField> view(data);
    (void)detail::read(reader, data.uint32Field);
    (void)detail::read(reader, data.compoundField);
    (void)detail::read(reader, data.stringField);
    return view;
}

} // namespace detail
} // namespace zserio

namespace std
{

size_t hash<::zserio::View<::nds::data::struct_templated_field::StructTemplatedField>>::operator()(const ::zserio::View<::nds::data::struct_templated_field::StructTemplatedField>& view) const
{
    uint32_t result = ::zserio::HASH_SEED;
    result = ::zserio::calcHashCode(result, view.uint32Field());
    result = ::zserio::calcHashCode(result, view.compoundField());
    result = ::zserio::calcHashCode(result, view.stringField());
    return static_cast<size_t>(result);
}

} // namespace std
