/**
 * Automatically generated by Zserio C++17 generator version 0.5.0 using Zserio core 2.17.0.
 * Generator setup: stdAllocator.
 */

#ifndef NDS_VIEW_STRUCT_TEMPLATED_FIELD_STRUCT_TEMPLATED_FIELD_H
#define NDS_VIEW_STRUCT_TEMPLATED_FIELD_STRUCT_TEMPLATED_FIELD_H

#include <nds/data/struct_templated_field/StructTemplatedField.h>
#include <nds/view/struct_templated_field/Compound.h>
#include <nds/view/struct_templated_field/Field.h>

#include <zserio/View.h>

namespace zserio
{

template <>
class View<::nds::data::struct_templated_field::StructTemplatedField>
{
public:
    explicit View(const ::nds::data::struct_templated_field::StructTemplatedField& data) noexcept;

    View<::nds::data::struct_templated_field::Field<::zserio::UInt32>> uint32Field() const;
    View<::nds::data::struct_templated_field::Field<::nds::data::struct_templated_field::Compound>> compoundField() const;
    View<::nds::data::struct_templated_field::Field<::zserio::String>> stringField() const;

    const ::nds::data::struct_templated_field::StructTemplatedField& zserioData() const;

protected:
    View(const ::nds::data::struct_templated_field::StructTemplatedField& data, const View& other) noexcept;

private:
    const ::nds::data::struct_templated_field::StructTemplatedField* m_data;
};

bool operator==(const View<::nds::data::struct_templated_field::StructTemplatedField>& lhs, const View<::nds::data::struct_templated_field::StructTemplatedField>& rhs);
bool operator<(const View<::nds::data::struct_templated_field::StructTemplatedField>& lhs, const View<::nds::data::struct_templated_field::StructTemplatedField>& rhs);
bool operator!=(const View<::nds::data::struct_templated_field::StructTemplatedField>& lhs, const View<::nds::data::struct_templated_field::StructTemplatedField>& rhs);
bool operator>(const View<::nds::data::struct_templated_field::StructTemplatedField>& lhs, const View<::nds::data::struct_templated_field::StructTemplatedField>& rhs);
bool operator<=(const View<::nds::data::struct_templated_field::StructTemplatedField>& lhs, const View<::nds::data::struct_templated_field::StructTemplatedField>& rhs);
bool operator>=(const View<::nds::data::struct_templated_field::StructTemplatedField>& lhs, const View<::nds::data::struct_templated_field::StructTemplatedField>& rhs);

namespace detail
{

template <>
struct ObjectTraits<::nds::data::struct_templated_field::StructTemplatedField>
{
    static void validate(const View<::nds::data::struct_templated_field::StructTemplatedField>& view, ::std::string_view fieldName);

    static BitSize bitSizeOf(const View<::nds::data::struct_templated_field::StructTemplatedField>& view, BitSize bitPosition);

    static void write(BitStreamWriter& writer, const View<::nds::data::struct_templated_field::StructTemplatedField>& view);

    static View<::nds::data::struct_templated_field::StructTemplatedField> read(BitStreamReader& reader, ::nds::data::struct_templated_field::StructTemplatedField& data);
};

} // namespace detail
} // namespace zserio

namespace nds::view::struct_templated_field
{

using StructTemplatedField = ::zserio::View<::nds::data::struct_templated_field::StructTemplatedField>;

} // namespace nds::view::struct_templated_field

namespace std
{

template <>
struct hash<::zserio::View<::nds::data::struct_templated_field::StructTemplatedField>>
{
    size_t operator()(const ::zserio::View<::nds::data::struct_templated_field::StructTemplatedField>& view) const;
};

} // namespace std

#endif // NDS_VIEW_STRUCT_TEMPLATED_FIELD_STRUCT_TEMPLATED_FIELD_H
