/**
 * Automatically generated by Zserio C++17 generator version 0.5.0 using Zserio core 2.17.0.
 * Generator setup: stdAllocator.
 */

#ifndef STRUCT_TEMPLATED_FIELD_STRUCT_TEMPLATED_FIELD_H
#define STRUCT_TEMPLATED_FIELD_STRUCT_TEMPLATED_FIELD_H

#include <zserio/CppRuntimeVersion.h>
#if CPP17_EXTENSION_RUNTIME_VERSION_NUMBER != 5000
    #error Version mismatch between Zserio runtime library and Zserio C++ generator!
    #error Please update your Zserio runtime library to the version 0.5.0.
#endif

#include <memory>
#include <zserio/View.h>
#include <memory>
#include <zserio/String.h>
#include <zserio/Types.h>

#include <struct_templated_field/Compound.h>
#include <struct_templated_field/Field.h>

namespace struct_templated_field
{

struct StructTemplatedField
{
    using allocator_type = ::std::allocator<uint8_t>;
    using Data = StructTemplatedField;
    using View = ::zserio::View<StructTemplatedField>;

    StructTemplatedField() noexcept;
    explicit StructTemplatedField(const allocator_type& allocator) noexcept;

    StructTemplatedField(StructTemplatedField&&) = default;
    StructTemplatedField(StructTemplatedField&& other, const allocator_type& allocator);

    StructTemplatedField(const StructTemplatedField&) = default;
    StructTemplatedField(const StructTemplatedField& other, const allocator_type& allocator);

    StructTemplatedField& operator=(StructTemplatedField&&) = default;
    StructTemplatedField& operator=(const StructTemplatedField&) = default;

    ~StructTemplatedField() = default;

    StructTemplatedField(
            ::struct_templated_field::Field<::zserio::UInt32> uint32Field_,
            ::struct_templated_field::Field<::struct_templated_field::Compound> compoundField_,
            ::struct_templated_field::Field<::zserio::String> stringField_,
            const allocator_type& allocator = {});

    ::struct_templated_field::Field<::zserio::UInt32> uint32Field;
    ::struct_templated_field::Field<::struct_templated_field::Compound> compoundField;
    ::struct_templated_field::Field<::zserio::String> stringField;
};

bool operator==(const ::struct_templated_field::StructTemplatedField& lhs, const ::struct_templated_field::StructTemplatedField& rhs);
bool operator<(const ::struct_templated_field::StructTemplatedField& lhs, const ::struct_templated_field::StructTemplatedField& rhs);
bool operator!=(const ::struct_templated_field::StructTemplatedField& lhs, const ::struct_templated_field::StructTemplatedField& rhs);
bool operator>(const ::struct_templated_field::StructTemplatedField& lhs, const ::struct_templated_field::StructTemplatedField& rhs);
bool operator<=(const ::struct_templated_field::StructTemplatedField& lhs, const ::struct_templated_field::StructTemplatedField& rhs);
bool operator>=(const ::struct_templated_field::StructTemplatedField& lhs, const ::struct_templated_field::StructTemplatedField& rhs);

} // namespace struct_templated_field

namespace zserio
{

template <>
class View<::struct_templated_field::StructTemplatedField>
{
public:
    explicit View(const ::struct_templated_field::StructTemplatedField& data) noexcept;

    View<::struct_templated_field::Field<::zserio::UInt32>> uint32Field() const;
    View<::struct_templated_field::Field<::struct_templated_field::Compound>> compoundField() const;
    View<::struct_templated_field::Field<::zserio::String>> stringField() const;

    const ::struct_templated_field::StructTemplatedField& zserioData() const;

protected:
    View(const ::struct_templated_field::StructTemplatedField& data, const View& other) noexcept;

private:
    const ::struct_templated_field::StructTemplatedField* m_data;
};

bool operator==(const View<::struct_templated_field::StructTemplatedField>& lhs, const View<::struct_templated_field::StructTemplatedField>& rhs);
bool operator<(const View<::struct_templated_field::StructTemplatedField>& lhs, const View<::struct_templated_field::StructTemplatedField>& rhs);
bool operator!=(const View<::struct_templated_field::StructTemplatedField>& lhs, const View<::struct_templated_field::StructTemplatedField>& rhs);
bool operator>(const View<::struct_templated_field::StructTemplatedField>& lhs, const View<::struct_templated_field::StructTemplatedField>& rhs);
bool operator<=(const View<::struct_templated_field::StructTemplatedField>& lhs, const View<::struct_templated_field::StructTemplatedField>& rhs);
bool operator>=(const View<::struct_templated_field::StructTemplatedField>& lhs, const View<::struct_templated_field::StructTemplatedField>& rhs);

namespace detail
{

template <>
struct ObjectTraits<::struct_templated_field::StructTemplatedField>
{
    static void validate(const View<::struct_templated_field::StructTemplatedField>& view, ::std::string_view fieldName);

    static BitSize bitSizeOf(const View<::struct_templated_field::StructTemplatedField>& view, BitSize bitPosition);

    static void write(BitStreamWriter& writer, const View<::struct_templated_field::StructTemplatedField>& view);

    static View<::struct_templated_field::StructTemplatedField> read(BitStreamReader& reader, ::struct_templated_field::StructTemplatedField& data);
};

} // namespace detail
} // namespace zserio

namespace std
{

template <>
struct hash<::struct_templated_field::StructTemplatedField>
{
    size_t operator()(const ::struct_templated_field::StructTemplatedField& data) const;
};

template <>
struct hash<::zserio::View<::struct_templated_field::StructTemplatedField>>
{
    size_t operator()(const ::zserio::View<::struct_templated_field::StructTemplatedField>& view) const;
};

} // namespace std

#endif // STRUCT_TEMPLATED_FIELD_STRUCT_TEMPLATED_FIELD_H
