/**
 * Automatically generated by Zserio C++17 generator version 0.5.0 using Zserio core 2.17.0.
 * Generator setup: stdAllocator.
 */

#ifndef STRUCT_TEMPLATED_FIELD_COMPOUND_H
#define STRUCT_TEMPLATED_FIELD_COMPOUND_H

#include <zserio/CppRuntimeVersion.h>
#if CPP17_EXTENSION_RUNTIME_VERSION_NUMBER != 5000
    #error Version mismatch between Zserio runtime library and Zserio C++ generator!
    #error Please update your Zserio runtime library to the version 0.5.0.
#endif

#include <memory>
#include <zserio/View.h>
#include <memory>
#include <zserio/Types.h>

namespace struct_templated_field
{

struct Compound
{
    using allocator_type = ::std::allocator<uint8_t>;

    Compound() noexcept;
    explicit Compound(const allocator_type& allocator) noexcept;

    Compound(Compound&&) = default;
    Compound(Compound&& other, const allocator_type& allocator);

    Compound(const Compound&) = default;
    Compound(const Compound& other, const allocator_type& allocator);

    Compound& operator=(Compound&&) = default;
    Compound& operator=(const Compound&) = default;

    ~Compound() = default;

    explicit Compound(
            ::zserio::UInt32 value_,
            const allocator_type& allocator = {});

    ::zserio::UInt32 value;
};

bool operator==(const ::struct_templated_field::Compound& lhs, const ::struct_templated_field::Compound& rhs);
bool operator<(const ::struct_templated_field::Compound& lhs, const ::struct_templated_field::Compound& rhs);
bool operator!=(const ::struct_templated_field::Compound& lhs, const ::struct_templated_field::Compound& rhs);
bool operator>(const ::struct_templated_field::Compound& lhs, const ::struct_templated_field::Compound& rhs);
bool operator<=(const ::struct_templated_field::Compound& lhs, const ::struct_templated_field::Compound& rhs);
bool operator>=(const ::struct_templated_field::Compound& lhs, const ::struct_templated_field::Compound& rhs);

} // namespace struct_templated_field

namespace zserio
{

template <>
class View<::struct_templated_field::Compound>
{
public:
    explicit View(const ::struct_templated_field::Compound& data) noexcept;

    ::zserio::UInt32 value() const;

    const ::struct_templated_field::Compound& zserioData() const;

protected:
    View(const ::struct_templated_field::Compound& data, const View& other) noexcept;

private:
    const ::struct_templated_field::Compound* m_data;
};

bool operator==(const View<::struct_templated_field::Compound>& lhs, const View<::struct_templated_field::Compound>& rhs);
bool operator<(const View<::struct_templated_field::Compound>& lhs, const View<::struct_templated_field::Compound>& rhs);
bool operator!=(const View<::struct_templated_field::Compound>& lhs, const View<::struct_templated_field::Compound>& rhs);
bool operator>(const View<::struct_templated_field::Compound>& lhs, const View<::struct_templated_field::Compound>& rhs);
bool operator<=(const View<::struct_templated_field::Compound>& lhs, const View<::struct_templated_field::Compound>& rhs);
bool operator>=(const View<::struct_templated_field::Compound>& lhs, const View<::struct_templated_field::Compound>& rhs);

namespace detail
{

template <>
struct ObjectTraits<::struct_templated_field::Compound>
{
    static void validate(const View<::struct_templated_field::Compound>& view, ::std::string_view fieldName);

    static BitSize bitSizeOf(const View<::struct_templated_field::Compound>& view, BitSize bitPosition);

    static void write(BitStreamWriter& writer, const View<::struct_templated_field::Compound>& view);

    static View<::struct_templated_field::Compound> read(BitStreamReader& reader, ::struct_templated_field::Compound& data);
};

} // namespace detail
} // namespace zserio

namespace std
{

template <>
struct hash<::struct_templated_field::Compound>
{
    size_t operator()(const ::struct_templated_field::Compound& data) const;
};

template <>
struct hash<::zserio::View<::struct_templated_field::Compound>>
{
    size_t operator()(const ::zserio::View<::struct_templated_field::Compound>& view) const;
};

} // namespace std

#endif // STRUCT_TEMPLATED_FIELD_COMPOUND_H
