/**
 * Automatically generated by Zserio C++17 generator version 0.5.0 using Zserio core 2.17.0.
 * Generator setup: stdAllocator.
 */

#include <zserio/BitPositionUtil.h>
#include <zserio/BitStreamReader.h>
#include <zserio/BitStreamWriter.h>
#include <zserio/HashCodeUtil.h>

#include <nds/data/struct_templated_field/Compound.h>

namespace nds::data
{
namespace struct_templated_field
{


Compound::Compound() noexcept :
        Compound(allocator_type{})
{
}

Compound::Compound(const allocator_type&) noexcept :
        value()
{
}

Compound::Compound(Compound&& other, const allocator_type&) :
        value(other.value)
{
}

Compound::Compound(const Compound& other, const allocator_type&) :
        value(other.value)
{
}

Compound::Compound(
        ::zserio::UInt32 value_,
        const allocator_type&) :
        value(value_)
{
}

bool operator==(const Compound& lhs, const Compound& rhs)
{
    return ::std::tie(
            lhs.value)
            == ::std::tie(
            rhs.value);
}

bool operator<(const Compound& lhs, const Compound& rhs)
{
    return ::std::tie(
            lhs.value)
            < ::std::tie(
            rhs.value);
}

bool operator!=(const Compound& lhs, const Compound& rhs)
{
    return !(lhs == rhs);
}

bool operator>(const Compound& lhs, const Compound& rhs)
{
    return rhs < lhs;
}

bool operator<=(const Compound& lhs, const Compound& rhs)
{
    return !(rhs < lhs);
}

bool operator>=(const Compound& lhs, const Compound& rhs)
{
    return !(lhs < rhs);
}

} // namespace struct_templatd_field
} // namespace Data

namespace std
{

size_t hash<::nds::data::struct_templated_field::Compound>::operator()(const ::nds::data::struct_templated_field::Compound& data) const
{
    uint32_t result = ::zserio::HASH_SEED;
    result = ::zserio::calcHashCode(result, data.value);
    return static_cast<size_t>(result);
}

} // namespace std
