/**
 * Automatically generated by Zserio C++17 generator version 0.5.0 using Zserio core 2.17.0.
 * Generator setup: stdAllocator.
 */

#ifndef NDS_DATA_STRUCT_TEMPLATED_FIELD_COMPOUND_H
#define NDS_DATA_STRUCT_TEMPLATED_FIELD_COMPOUND_H

#include <zserio/CppRuntimeVersion.h>
#if CPP17_EXTENSION_RUNTIME_VERSION_NUMBER != 5000
    #error Version mismatch between Zserio runtime library and Zserio C++ generator!
    #error Please update your Zserio runtime library to the version 0.5.0.
#endif

#include <memory>
#include <memory>
#include <zserio/Types.h>

namespace
nds::data
{
namespace struct_templated_field
{

struct Compound
{
    using allocator_type = ::std::allocator<uint8_t>;

    Compound() noexcept;
    explicit Compound(const allocator_type& allocator) noexcept;

    Compound(Compound&&) = default;
    Compound(Compound&& other, const allocator_type& allocator);

    Compound(const Compound&) = default;
    Compound(const Compound& other, const allocator_type& allocator);

    Compound& operator=(Compound&&) = default;
    Compound& operator=(const Compound&) = default;

    ~Compound() = default;

    explicit Compound(
        ::zserio::UInt32 value_,
        const allocator_type& allocator = {});

    ::zserio::UInt32 value;
};

bool operator==(const Compound& lhs, const Compound& rhs);
bool operator<(const Compound& lhs, const Compound& rhs);
bool operator!=(const Compound& lhs, const Compound& rhs);
bool operator>(const Compound& lhs, const Compound& rhs);
bool operator<=(const Compound& lhs, const Compound& rhs);
bool operator>=(const Compound& lhs, const Compound& rhs);

} // namespace struct_templated_field
} // namespace Data

namespace std
{

template <>
struct hash<::nds::data::struct_templated_field::Compound>
{
    size_t operator()(const ::nds::data::struct_templated_field::Compound& data) const;
};

} // namespace std

#endif // NDS_DATA_STRUCT_TEMPLATED_FIELD_COMPOUND_H
