/**
 * Automatically generated by Zserio C++17 generator version 0.5.0 using Zserio core 2.17.0.
 * Generator setup: stdAllocator.
 */

#ifndef NDS_DATA_STRUCT_TEMPLATED_FIELD_FIELD_H
#define NDS_DATA_STRUCT_TEMPLATED_FIELD_FIELD_H

#include <zserio/CppRuntimeVersion.h>
#if CPP17_EXTENSION_RUNTIME_VERSION_NUMBER != 5000
    #error Version mismatch between Zserio runtime library and Zserio C++ generator!
    #error Please update your Zserio runtime library to the version 0.5.0.
#endif

#include <memory>

#include <zserio/Bitmasks.h>
#include <zserio/BitPositionUtil.h>
#include <zserio/BitStreamReader.h>
#include <zserio/BitStreamWriter.h>
#include <zserio/Enums.h>
#include <zserio/HashCodeUtil.h>
#include <zserio/GenericAccessor.h>
#include <memory>
#include <zserio/Vector.h>

namespace nds::data
{
namespace struct_templated_field
{

template <typename T>
struct Field
{
    using allocator_type = ::std::allocator<uint8_t>;

    Field() noexcept :
        Field(allocator_type{})
    {}

    explicit Field(const allocator_type& allocator) noexcept :
            value(::zserio::constructWithAllocator<T>(allocator)),
            arr(::zserio::constructWithAllocator<::zserio::Vector<T>>(allocator))
    {
    }

    Field(Field&&) = default;

    Field(Field&& other, const allocator_type& allocator) :
            value(::zserio::constructWithAllocator<T>(allocator, std::move(other.value))),
            arr(::zserio::constructWithAllocator<::zserio::Vector<T>>(allocator, std::move(other.arr)))
    {
    }

    Field(const Field&) = default;

    Field(const Field& other, const allocator_type& allocator) :
            value(::zserio::constructWithAllocator<T>(allocator, other.value)),
            arr(::zserio::constructWithAllocator<::zserio::Vector<T>>(allocator, other.arr))
    {
    }

    Field& operator=(Field&&) = default;
    Field& operator=(const Field&) = default;

    ~Field() = default;

    Field(
            T value_,
            ::zserio::Vector<T> arr_,
            const allocator_type& allocator = {}) :
            value(::zserio::constructWithAllocator<T>(allocator, ::std::move(value_))),
            arr(::zserio::constructWithAllocator<::zserio::Vector<T>>(allocator, ::std::move(arr_)))
    {}

    T value;
    ::zserio::Vector<T> arr;
};

template <typename T>
bool operator==(const Field<T>& lhs, const Field<T>& rhs)
{
    return ::std::tie(
            lhs.value,
            lhs.arr)
            == ::std::tie(
            rhs.value,
            rhs.arr);
}

template <typename T>
bool operator<(const Field<T>& lhs, const Field<T>& rhs)
{
    return ::std::tie(
            lhs.value,
            lhs.arr)
            < ::std::tie(
            rhs.value,
            rhs.arr);
}

template <typename T>
bool operator!=(const Field<T>& lhs, const Field<T>& rhs)
{
    return !(lhs == rhs);
}

template <typename T>
bool operator>(const Field<T>& lhs, const Field<T>& rhs)
{
    return rhs < lhs;
}

template <typename T>
bool operator<=(const Field<T>& lhs, const Field<T>& rhs)
{
    return !(rhs < lhs);
}

template <typename T>
bool operator>=(const Field<T>& lhs, const Field<T>& rhs)
{
    return !(lhs < rhs);
}

} // namespace struct_templated_field
} // namespace Data

namespace std
{

template <typename T>
struct hash<::nds::data::struct_templated_field::Field<T>>
{
    size_t operator()(const ::nds::data::struct_templated_field::Field<T>& data) const
    {
        uint32_t result = ::zserio::HASH_SEED;
        result = ::zserio::calcHashCode(result, data.value);
        result = ::zserio::calcHashCode(result, data.arr);
        return static_cast<size_t>(result);
    }
};

} // namespace std

#endif // NDS_DATA_STRUCT_TEMPLATED_FIELD_FIELD_H
