/**
 * Automatically generated by Zserio C++17 generator version 0.5.0 using Zserio core 2.17.0.
 * Generator setup: stdAllocator.
 */

#ifndef NDS_DATA_STRUCT_TEMPLATED_FIELD_STRUCT_TEMPLATED_FIELD_H
#define NDS_DATA_STRUCT_TEMPLATED_FIELD_STRUCT_TEMPLATED_FIELD_H

#include <zserio/CppRuntimeVersion.h>
#if CPP17_EXTENSION_RUNTIME_VERSION_NUMBER != 5000
    #error Version mismatch between Zserio runtime library and Zserio C++ generator!
    #error Please update your Zserio runtime library to the version 0.5.0.
#endif

#include <memory>
#include <memory>
#include <zserio/String.h>
#include <zserio/Types.h>

#include <nds/data/struct_templated_field/Compound.h>
#include <nds/data/struct_templated_field/Field.h>

namespace nds::data
{
namespace struct_templated_field
{

struct StructTemplatedField
{
    using allocator_type = ::std::allocator<uint8_t>;

    StructTemplatedField() noexcept;
    explicit StructTemplatedField(const allocator_type& allocator) noexcept;

    StructTemplatedField(StructTemplatedField&&) = default;
    StructTemplatedField(StructTemplatedField&& other, const allocator_type& allocator);

    StructTemplatedField(const StructTemplatedField&) = default;
    StructTemplatedField(const StructTemplatedField& other, const allocator_type& allocator);

    StructTemplatedField& operator=(StructTemplatedField&&) = default;
    StructTemplatedField& operator=(const StructTemplatedField&) = default;

    ~StructTemplatedField() = default;

    StructTemplatedField(
            ::nds::data::struct_templated_field::Field<::zserio::UInt32> uint32Field_,
            ::nds::data::struct_templated_field::Field<::nds::data::struct_templated_field::Compound> compoundField_,
            ::nds::data::struct_templated_field::Field<::zserio::String> stringField_,
            const allocator_type& allocator = {});

    ::nds::data::struct_templated_field::Field<::zserio::UInt32> uint32Field;
    ::nds::data::struct_templated_field::Field<::nds::data::struct_templated_field::Compound> compoundField;
    ::nds::data::struct_templated_field::Field<::zserio::String> stringField;
};

bool operator==(const StructTemplatedField& lhs, const StructTemplatedField& rhs);
bool operator<(const StructTemplatedField& lhs, const StructTemplatedField& rhs);
bool operator!=(const StructTemplatedField& lhs, const StructTemplatedField& rhs);
bool operator>(const StructTemplatedField& lhs, const StructTemplatedField& rhs);
bool operator<=(const StructTemplatedField& lhs, const StructTemplatedField& rhs);
bool operator>=(const StructTemplatedField& lhs, const StructTemplatedField& rhs);

} // namespace StructTemplatedField
} // namespace Data

namespace std
{

template <>
struct hash<::nds::data::struct_templated_field::StructTemplatedField>
{
    size_t operator()(const ::nds::data::struct_templated_field::StructTemplatedField& data) const;
};

} // namespace std

#endif // NDS_DATA_STRUCT_TEMPLATED_FIELD_STRUCT_TEMPLATED_FIELD_H
