/**
 * Automatically generated by Zserio C++17 generator version 0.5.0 using Zserio core 2.17.0.
 * Generator setup: stdAllocator.
 */

#include <zserio/BitPositionUtil.h>
#include <zserio/BitStreamReader.h>
#include <zserio/BitStreamWriter.h>
#include <zserio/HashCodeUtil.h>

#include <nds/data/struct_templated_field/StructTemplatedField.h>

namespace nds::data
{
namespace struct_templated_field
{

StructTemplatedField::StructTemplatedField() noexcept :
    StructTemplatedField(allocator_type{})
{
}

StructTemplatedField::StructTemplatedField(const allocator_type& allocator) noexcept :
        uint32Field(allocator),
        compoundField(allocator),
        stringField(allocator)
{
}

StructTemplatedField::StructTemplatedField(StructTemplatedField&& other, const allocator_type& allocator) :
        uint32Field(std::move(other.uint32Field), allocator),
        compoundField(std::move(other.compoundField), allocator),
        stringField(std::move(other.stringField), allocator)
{
}

StructTemplatedField::StructTemplatedField(const StructTemplatedField& other, const allocator_type& allocator) :
        uint32Field(other.uint32Field, allocator),
        compoundField(other.compoundField, allocator),
        stringField(other.stringField, allocator)
{
}

StructTemplatedField::StructTemplatedField(
        ::nds::data::struct_templated_field::Field<::zserio::UInt32> uint32Field_,
        ::nds::data::struct_templated_field::Field<::nds::data::struct_templated_field::Compound> compoundField_,
        ::nds::data::struct_templated_field::Field<::zserio::String> stringField_,
        const allocator_type& allocator) :
        uint32Field(::std::move(uint32Field_), allocator),
        compoundField(::std::move(compoundField_), allocator),
        stringField(::std::move(stringField_), allocator)
{
}

bool operator==(const StructTemplatedField& lhs, const StructTemplatedField& rhs)
{
    return ::std::tie(
            lhs.uint32Field,
            lhs.compoundField,
            lhs.stringField)
            == ::std::tie(
            rhs.uint32Field,
            rhs.compoundField,
            rhs.stringField);
}

bool operator<(const StructTemplatedField& lhs, const StructTemplatedField& rhs)
{
    return ::std::tie(
            lhs.uint32Field,
            lhs.compoundField,
            lhs.stringField)
            < ::std::tie(
            rhs.uint32Field,
            rhs.compoundField,
            rhs.stringField);
}

bool operator!=(const StructTemplatedField& lhs, const StructTemplatedField& rhs)
{
    return !(lhs == rhs);
}

bool operator>(const StructTemplatedField& lhs, const StructTemplatedField& rhs)
{
    return rhs < lhs;
}

bool operator<=(const StructTemplatedField& lhs, const StructTemplatedField& rhs)
{
    return !(rhs < lhs);
}

bool operator>=(const StructTemplatedField& lhs, const StructTemplatedField& rhs)
{
    return !(lhs < rhs);
}

} // namespace struct_templated_field
} // namespace Data

namespace std
{

size_t hash<::nds::data::struct_templated_field::StructTemplatedField>::operator()(const ::nds::data::struct_templated_field::StructTemplatedField& data) const
{
    uint32_t result = ::zserio::HASH_SEED;
    result = ::zserio::calcHashCode(result, data.uint32Field);
    result = ::zserio::calcHashCode(result, data.compoundField);
    result = ::zserio::calcHashCode(result, data.stringField);
    return static_cast<size_t>(result);
}

} // namespace std
