/**
 * Automatically generated by Zserio C++17 generator version 0.5.0 using Zserio core 2.17.0.
 * Generator setup: stdAllocator.
 */

#ifndef STRUCT_TEMPLATED_FIELD_FIELD_H
#define STRUCT_TEMPLATED_FIELD_FIELD_H

#include <zserio/CppRuntimeVersion.h>
#if CPP17_EXTENSION_RUNTIME_VERSION_NUMBER != 5000
    #error Version mismatch between Zserio runtime library and Zserio C++ generator!
    #error Please update your Zserio runtime library to the version 0.5.0.
#endif

#include <memory>

#include <zserio/Bitmasks.h>
#include <zserio/BitPositionUtil.h>
#include <zserio/BitStreamReader.h>
#include <zserio/BitStreamWriter.h>
#include <zserio/Enums.h>
#include <zserio/HashCodeUtil.h>
#include <zserio/View.h>
#include <zserio/GenericAccessor.h>
#include <memory>
#include <zserio/ArrayView.h>
#include <zserio/Vector.h>

namespace Data
{
namespace struct_templated_field
{

template <typename T>
struct Field
{
    using allocator_type = ::std::allocator<uint8_t>;

    Field() noexcept :
        Field(allocator_type{})
    {}

    explicit Field(const allocator_type& allocator) noexcept :
            value(::zserio::constructWithAllocator<T>(allocator)),
            arr(::zserio::constructWithAllocator<::zserio::Vector<T>>(allocator))
    {
    }

    Field(Field&&) = default;

    Field(Field&& other, const allocator_type& allocator) :
            value(::zserio::constructWithAllocator<T>(allocator, std::move(other.value))),
            arr(::zserio::constructWithAllocator<::zserio::Vector<T>>(allocator, std::move(other.arr)))
    {
    }

    Field(const Field&) = default;

    Field(const Field& other, const allocator_type& allocator) :
            value(::zserio::constructWithAllocator<T>(allocator, other.value)),
            arr(::zserio::constructWithAllocator<::zserio::Vector<T>>(allocator, other.arr))
    {
    }

    Field& operator=(Field&&) = default;
    Field& operator=(const Field&) = default;

    ~Field() = default;

    Field(
            T value_,
            ::zserio::Vector<T> arr_,
            const allocator_type& allocator = {}) :
            value(::zserio::constructWithAllocator<T>(allocator, ::std::move(value_))),
            arr(::zserio::constructWithAllocator<::zserio::Vector<T>>(allocator, ::std::move(arr_)))
    {}

    T value;
    ::zserio::Vector<T> arr;
};

template <typename T>
bool operator==(const Field<T>& lhs, const Field<T>& rhs)
{
    return ::std::tie(
            lhs.value,
            lhs.arr)
            == ::std::tie(
            rhs.value,
            rhs.arr);
}

template <typename T>
bool operator<(const Field<T>& lhs, const Field<T>& rhs)
{
    return ::std::tie(
            lhs.value,
            lhs.arr)
            < ::std::tie(
            rhs.value,
            rhs.arr);
}

template <typename T>
bool operator!=(const Field<T>& lhs, const Field<T>& rhs)
{
    return !(lhs == rhs);
}

template <typename T>
bool operator>(const Field<T>& lhs, const Field<T>& rhs)
{
    return rhs < lhs;
}

template <typename T>
bool operator<=(const Field<T>& lhs, const Field<T>& rhs)
{
    return !(rhs < lhs);
}

template <typename T>
bool operator>=(const Field<T>& lhs, const Field<T>& rhs)
{
    return !(lhs < rhs);
}

} // namespace struct_templated_field
} // namespace Data

namespace zserio
{

template <typename T>
class View<::Data::struct_templated_field::Field<T>>
{
public:
    explicit View(const ::Data::struct_templated_field::Field<T>& data) noexcept:
            m_data(&data)
    {}

    view_type_t<T> value() const
    {
        if constexpr (detail::is_view_v<view_type_t<T>>)
        {
            return view_type_t<T>(m_data->value);
        }
        else
        {
            return m_data->value;
        }
    }

    ArrayView<const T> arr() const
    {
        return ArrayView<const T>(m_data->arr);
    }

    const ::Data::struct_templated_field::Field<T>& zserioData() const;

protected:
    View(const ::Data::struct_templated_field::Field<T>& data, const View&) noexcept :
            m_data(&data)
    {}

private:
    const ::Data::struct_templated_field::Field<T>* m_data;
};

template <typename T>
bool operator==(const View<::Data::struct_templated_field::Field<T>>& lhs, const View<::Data::struct_templated_field::Field<T>>& rhs)
{
    return lhs.value() == rhs.value() &&
            lhs.arr() == rhs.arr();
}

template <typename T>
bool operator<(const View<::Data::struct_templated_field::Field<T>>& lhs, const View<::Data::struct_templated_field::Field<T>>& rhs)
{
    if (lhs.value() != rhs.value())
    {
        return lhs.value() < rhs.value();
    }
    if (lhs.arr() != rhs.arr())
    {
        return lhs.arr() < rhs.arr();
    }

    return false;
}

template <typename T>
bool operator!=(const View<::Data::struct_templated_field::Field<T>>& lhs, const View<::Data::struct_templated_field::Field<T>>& rhs)
{
    return !(lhs == rhs);
}

template <typename T>
bool operator>(const View<::Data::struct_templated_field::Field<T>>& lhs, const View<::Data::struct_templated_field::Field<T>>& rhs)
{
    return rhs < lhs;
}

template <typename T>
bool operator<=(const View<::Data::struct_templated_field::Field<T>>& lhs, const View<::Data::struct_templated_field::Field<T>>& rhs)
{
    return !(rhs < lhs);
}

template <typename T>
bool operator>=(const View<::Data::struct_templated_field::Field<T>>& lhs, const View<::Data::struct_templated_field::Field<T>>& rhs)
{
    return !(lhs < rhs);
}

namespace detail
{

template <typename T>
struct ObjectTraits<::Data::struct_templated_field::Field<T>>
{
    static void validate(const View<::Data::struct_templated_field::Field<T>>& view, ::std::string_view)
    {
        detail::validate(view.value(), "'Field.value'");
        detail::validate<ArrayType::NORMAL>(view.arr(), "'Field.arr'", static_cast<size_t>(3));
    }

    static BitSize bitSizeOf(const View<::Data::struct_templated_field::Field<T>>& view, BitSize bitPosition)
    {
        BitSize endBitPosition = bitPosition;

        auto value_ = view.value();
        endBitPosition += detail::bitSizeOf(value_, endBitPosition);
        auto arr_ = view.arr();
        endBitPosition += detail::bitSizeOf<ArrayType::NORMAL>(arr_, endBitPosition);

        return endBitPosition - bitPosition;
    }

    static void write(BitStreamWriter& writer, const View<::Data::struct_templated_field::Field<T>>& view)
    {
        auto value_ = view.value();
        detail::write(writer, value_);
        auto arr_ = view.arr();
        detail::write<ArrayType::NORMAL>(writer, arr_);
    }

    static View<::Data::struct_templated_field::Field<T>> read(BitStreamReader& reader, ::Data::struct_templated_field::Field<T>& data)
    {
        View<::Data::struct_templated_field::Field<T>> view(data);
        detail::read(reader, data.value);
        detail::read<ArrayType::NORMAL>(reader, data.arr, static_cast<size_t>(3));
        return view;
    }
};

} // namespace detail
} // namespace zserio

namespace View
{
namespace struct_templated_field
{


template <typename T>
using Field = ::zserio::View<Data::struct_templated_field::Field<T>>;

} // namespace struct_templated_field
} // namespace View

namespace std
{

template <typename T>
struct hash<::Data::struct_templated_field::Field<T>>
{
    size_t operator()(const ::Data::struct_templated_field::Field<T>& data) const
    {
        uint32_t result = ::zserio::HASH_SEED;
        result = ::zserio::calcHashCode(result, data.value);
        result = ::zserio::calcHashCode(result, data.arr);
        return static_cast<size_t>(result);
    }
};

template <typename T>
struct hash<::zserio::View<::Data::struct_templated_field::Field<T>>>
{
    size_t operator()(const ::zserio::View<::Data::struct_templated_field::Field<T>>& view) const
    {
        uint32_t result = ::zserio::HASH_SEED;
        result = ::zserio::calcHashCode(result, view.value());
        result = ::zserio::calcHashCode(result, view.arr());
        return static_cast<size_t>(result);
    }
};

} // namespace std

#endif // STRUCT_TEMPLATED_FIELD_FIELD_H
