/**
 * Automatically generated by Zserio C++17 generator version 0.5.0 using Zserio core 2.17.0.
 * Generator setup: stdAllocator.
 */

#ifndef STRUCT_TEMPLATED_FIELD_STRUCT_TEMPLATED_FIELD_H
#define STRUCT_TEMPLATED_FIELD_STRUCT_TEMPLATED_FIELD_H

#include <zserio/CppRuntimeVersion.h>
#if CPP17_EXTENSION_RUNTIME_VERSION_NUMBER != 5000
    #error Version mismatch between Zserio runtime library and Zserio C++ generator!
    #error Please update your Zserio runtime library to the version 0.5.0.
#endif

#include <memory>
#include <zserio/View.h>
#include <memory>
#include <zserio/String.h>
#include <zserio/Types.h>

#include <struct_templated_field/Compound.h>
#include <struct_templated_field/Field.h>

namespace Data
{
namespace struct_templated_field
{

struct StructTemplatedField
{
    using allocator_type = ::std::allocator<uint8_t>;

    StructTemplatedField() noexcept;
    explicit StructTemplatedField(const allocator_type& allocator) noexcept;

    StructTemplatedField(StructTemplatedField&&) = default;
    StructTemplatedField(StructTemplatedField&& other, const allocator_type& allocator);

    StructTemplatedField(const StructTemplatedField&) = default;
    StructTemplatedField(const StructTemplatedField& other, const allocator_type& allocator);

    StructTemplatedField& operator=(StructTemplatedField&&) = default;
    StructTemplatedField& operator=(const StructTemplatedField&) = default;

    ~StructTemplatedField() = default;

    StructTemplatedField(
            ::Data::struct_templated_field::Field<::zserio::UInt32> uint32Field_,
            ::Data::struct_templated_field::Field<::Data::struct_templated_field::Compound> compoundField_,
            ::Data::struct_templated_field::Field<::zserio::String> stringField_,
            const allocator_type& allocator = {});

    ::Data::struct_templated_field::Field<::zserio::UInt32> uint32Field;
    ::Data::struct_templated_field::Field<::Data::struct_templated_field::Compound> compoundField;
    ::Data::struct_templated_field::Field<::zserio::String> stringField;
};

bool operator==(const StructTemplatedField& lhs, const StructTemplatedField& rhs);
bool operator<(const StructTemplatedField& lhs, const StructTemplatedField& rhs);
bool operator!=(const StructTemplatedField& lhs, const StructTemplatedField& rhs);
bool operator>(const StructTemplatedField& lhs, const StructTemplatedField& rhs);
bool operator<=(const StructTemplatedField& lhs, const StructTemplatedField& rhs);
bool operator>=(const StructTemplatedField& lhs, const StructTemplatedField& rhs);

} // namespace StructTemplatedField
} // namespace Data

namespace zserio
{

template <>
class View<::Data::struct_templated_field::StructTemplatedField>
{
public:
    explicit View(const ::Data::struct_templated_field::StructTemplatedField& data) noexcept;

    View<::Data::struct_templated_field::Field<::zserio::UInt32>> uint32Field() const;
    View<::Data::struct_templated_field::Field<::Data::struct_templated_field::Compound>> compoundField() const;
    View<::Data::struct_templated_field::Field<::zserio::String>> stringField() const;

    const ::Data::struct_templated_field::StructTemplatedField& zserioData() const;

protected:
    View(const ::Data::struct_templated_field::StructTemplatedField& data, const View& other) noexcept;

private:
    const ::Data::struct_templated_field::StructTemplatedField* m_data;
};

bool operator==(const View<::Data::struct_templated_field::StructTemplatedField>& lhs, const View<::Data::struct_templated_field::StructTemplatedField>& rhs);
bool operator<(const View<::Data::struct_templated_field::StructTemplatedField>& lhs, const View<::Data::struct_templated_field::StructTemplatedField>& rhs);
bool operator!=(const View<::Data::struct_templated_field::StructTemplatedField>& lhs, const View<::Data::struct_templated_field::StructTemplatedField>& rhs);
bool operator>(const View<::Data::struct_templated_field::StructTemplatedField>& lhs, const View<::Data::struct_templated_field::StructTemplatedField>& rhs);
bool operator<=(const View<::Data::struct_templated_field::StructTemplatedField>& lhs, const View<::Data::struct_templated_field::StructTemplatedField>& rhs);
bool operator>=(const View<::Data::struct_templated_field::StructTemplatedField>& lhs, const View<::Data::struct_templated_field::StructTemplatedField>& rhs);

namespace detail
{

template <>
struct ObjectTraits<::Data::struct_templated_field::StructTemplatedField>
{
    static void validate(const View<::Data::struct_templated_field::StructTemplatedField>& view, ::std::string_view fieldName);

    static BitSize bitSizeOf(const View<::Data::struct_templated_field::StructTemplatedField>& view, BitSize bitPosition);

    static void write(BitStreamWriter& writer, const View<::Data::struct_templated_field::StructTemplatedField>& view);

    static View<::Data::struct_templated_field::StructTemplatedField> read(BitStreamReader& reader, ::Data::struct_templated_field::StructTemplatedField& data);
};

} // namespace detail
} // namespace zserio

namespace View
{
namespace struct_templated_field
{

using StructTemplatedField = ::zserio::View<Data::struct_templated_field::StructTemplatedField>;

}
}

namespace std
{

template <>
struct hash<::Data::struct_templated_field::StructTemplatedField>
{
    size_t operator()(const ::Data::struct_templated_field::StructTemplatedField& data) const;
};

template <>
struct hash<::zserio::View<::Data::struct_templated_field::StructTemplatedField>>
{
    size_t operator()(const ::zserio::View<::Data::struct_templated_field::StructTemplatedField>& view) const;
};

} // namespace std

#endif // STRUCT_TEMPLATED_FIELD_STRUCT_TEMPLATED_FIELD_H
