/**
 * Automatically generated by Zserio C++17 generator version 0.5.0 using Zserio core 2.17.0.
 * Generator setup: stdAllocator.
 */

#ifndef STRUCT_TEMPLATED_FIELD_COMPOUND_H
#define STRUCT_TEMPLATED_FIELD_COMPOUND_H

#include <zserio/CppRuntimeVersion.h>
#if CPP17_EXTENSION_RUNTIME_VERSION_NUMBER != 5000
    #error Version mismatch between Zserio runtime library and Zserio C++ generator!
    #error Please update your Zserio runtime library to the version 0.5.0.
#endif

#include <memory>
#include <zserio/View.h>
#include <memory>
#include <zserio/Types.h>

namespace struct_templated_field
{
namespace Compound
{

struct Data
{
    using allocator_type = ::std::allocator<uint8_t>;

    Data() noexcept;
    explicit Data(const allocator_type& allocator) noexcept;

    Data(Data&&) = default;
    Data(Data&& other, const allocator_type& allocator);

    Data(const Data&) = default;
    Data(const Data& other, const allocator_type& allocator);

    Data& operator=(Data&&) = default;
    Data& operator=(const Data&) = default;

    ~Data() = default;

    explicit Data(
        ::zserio::UInt32 value_,
        const allocator_type& allocator = {});

    ::zserio::UInt32 value;
};

bool operator==(const Data& lhs, const Data& rhs);
bool operator<(const Data& lhs, const Data& rhs);
bool operator!=(const Data& lhs, const Data& rhs);
bool operator>(const Data& lhs, const Data& rhs);
bool operator<=(const Data& lhs, const Data& rhs);
bool operator>=(const Data& lhs, const Data& rhs);

} // namespace Compound
} // namespace struct_templated_field

namespace zserio
{

template <>
class View<::struct_templated_field::Compound::Data>
{
public:
    explicit View(const ::struct_templated_field::Compound::Data& data) noexcept;

    ::zserio::UInt32 value() const;

    const ::struct_templated_field::Compound::Data& zserioData() const;

protected:
    View(const ::struct_templated_field::Compound::Data& data, const View& other) noexcept;

private:
    const ::struct_templated_field::Compound::Data* m_data;
};

bool operator==(const View<::struct_templated_field::Compound::Data>& lhs, const View<::struct_templated_field::Compound::Data>& rhs);
bool operator<(const View<::struct_templated_field::Compound::Data>& lhs, const View<::struct_templated_field::Compound::Data>& rhs);
bool operator!=(const View<::struct_templated_field::Compound::Data>& lhs, const View<::struct_templated_field::Compound::Data>& rhs);
bool operator>(const View<::struct_templated_field::Compound::Data>& lhs, const View<::struct_templated_field::Compound::Data>& rhs);
bool operator<=(const View<::struct_templated_field::Compound::Data>& lhs, const View<::struct_templated_field::Compound::Data>& rhs);
bool operator>=(const View<::struct_templated_field::Compound::Data>& lhs, const View<::struct_templated_field::Compound::Data>& rhs);

namespace detail
{

template <>
struct ObjectTraits<::struct_templated_field::Compound::Data>
{
    static void validate(const View<::struct_templated_field::Compound::Data>& view, ::std::string_view fieldName);

    static BitSize bitSizeOf(const View<::struct_templated_field::Compound::Data>& view, BitSize bitPosition);

    static void write(BitStreamWriter& writer, const View<::struct_templated_field::Compound::Data>& view);

    static View<::struct_templated_field::Compound::Data> read(BitStreamReader& reader, ::struct_templated_field::Compound::Data& data);
};

} // namespace detail

} // namespace zserio

namespace struct_templated_field
{
namespace Compound
{

using View = ::zserio::View<Data>;

} // namespace Compound
} // namespace struct_templated_field

namespace std
{

template <>
struct hash<::struct_templated_field::Compound::Data>
{
    size_t operator()(const ::struct_templated_field::Compound::Data& data) const;
};

template <>
struct hash<::zserio::View<::struct_templated_field::Compound::Data>>
{
    size_t operator()(const ::zserio::View<::struct_templated_field::Compound::Data>& view) const;
};

} // namespace std

#endif // STRUCT_TEMPLATED_FIELD_Compound::Data_H
