/**
 * Automatically generated by Zserio C++17 generator version 0.5.0 using Zserio core 2.17.0.
 * Generator setup: stdAllocator.
 */

#include <zserio/BitPositionUtil.h>
#include <zserio/BitStreamReader.h>
#include <zserio/BitStreamWriter.h>
#include <zserio/HashCodeUtil.h>

#include <struct_templated_field/Compound.h>

namespace struct_templated_field
{
namespace Compound
{

Data::Data() noexcept :
        Data(allocator_type{})
{
}

Data::Data(const allocator_type&) noexcept :
        value()
{
}

Data::Data(Data&& other, const allocator_type&) :
        value(other.value)
{
}

Data::Data(const Data& other, const allocator_type&) :
        value(other.value)
{
}

Data::Data(
        ::zserio::UInt32 value_,
        const allocator_type&) :
        value(value_)
{
}

bool operator==(const Data& lhs, const Data& rhs)
{
    return ::std::tie(
            lhs.value)
            == ::std::tie(
            rhs.value);
}

bool operator<(const Data& lhs, const Data& rhs)
{
    return ::std::tie(
            lhs.value)
            < ::std::tie(
            rhs.value);
}

bool operator!=(const Data& lhs, const Data& rhs)
{
    return !(lhs == rhs);
}

bool operator>(const Data& lhs, const Data& rhs)
{
    return rhs < lhs;
}

bool operator<=(const Data& lhs, const Data& rhs)
{
    return !(rhs < lhs);
}

bool operator>=(const Data& lhs, const Data& rhs)
{
    return !(lhs < rhs);
}

} // namespace Data
} // namespace struct_templatd_field

namespace zserio
{

View<::struct_templated_field::Compound::Data>::View(const ::struct_templated_field::Compound::Data& data) noexcept :
        m_data(&data)
{}

View<::struct_templated_field::Compound::Data>::View(const ::struct_templated_field::Compound::Data& data,
        const View&) noexcept :
        m_data(&data)
{}

::zserio::UInt32 View<::struct_templated_field::Compound::Data>::value() const
{
    return m_data->value;
}

const ::struct_templated_field::Compound::Data& View<::struct_templated_field::Compound::Data>::zserioData() const
{
    return *m_data;
}

bool operator==(const View<::struct_templated_field::Compound::Data>& lhs, const View<::struct_templated_field::Compound::Data>& rhs)
{
    return lhs.value() == rhs.value();
}

bool operator<(const View<::struct_templated_field::Compound::Data>& lhs, const View<::struct_templated_field::Compound::Data>& rhs)
{
    if (lhs.value() != rhs.value())
    {
        return lhs.value() < rhs.value();
    }

    return false;
}

bool operator!=(const View<::struct_templated_field::Compound::Data>& lhs, const View<::struct_templated_field::Compound::Data>& rhs)
{
    return !(lhs == rhs);
}

bool operator>(const View<::struct_templated_field::Compound::Data>& lhs, const View<::struct_templated_field::Compound::Data>& rhs)
{
    return rhs < lhs;
}

bool operator<=(const View<::struct_templated_field::Compound::Data>& lhs, const View<::struct_templated_field::Compound::Data>& rhs)
{
    return !(rhs < lhs);
}

bool operator>=(const View<::struct_templated_field::Compound::Data>& lhs, const View<::struct_templated_field::Compound::Data>& rhs)
{
    return !(lhs < rhs);
}

namespace detail
{

void ObjectTraits<::struct_templated_field::Compound::Data>::validate(const View<::struct_templated_field::Compound::Data>& view, ::std::string_view)
{
    detail::validate(view.value(), "'Compound.value'");
}

BitSize ObjectTraits<::struct_templated_field::Compound::Data>::bitSizeOf(const View<::struct_templated_field::Compound::Data>& view, BitSize bitPosition)
{
    BitSize endBitPosition = bitPosition;

    auto value_ = view.value();
    endBitPosition += detail::bitSizeOf(value_, endBitPosition);

    return endBitPosition - bitPosition;
}

void ObjectTraits<::struct_templated_field::Compound::Data>::write(BitStreamWriter& writer, const View<::struct_templated_field::Compound::Data>& view)
{
    auto value_ = view.value();
    detail::write(writer, value_);
}

View<::struct_templated_field::Compound::Data> ObjectTraits<::struct_templated_field::Compound::Data>::read(BitStreamReader& reader, ::struct_templated_field::Compound::Data& data)
{
    View<::struct_templated_field::Compound::Data> view(data);
    detail::read(reader, data.value);
    return view;
}

} // namespace detail
} // namespace zserio

namespace std
{

size_t hash<::struct_templated_field::Compound::Data>::operator()(const ::struct_templated_field::Compound::Data& data) const
{
    uint32_t result = ::zserio::HASH_SEED;
    result = ::zserio::calcHashCode(result, data.value);
    return static_cast<size_t>(result);
}

size_t hash<::zserio::View<::struct_templated_field::Compound::Data>>::operator()(const ::zserio::View<::struct_templated_field::Compound::Data>& view) const
{
    uint32_t result = ::zserio::HASH_SEED;
    result = ::zserio::calcHashCode(result, view.value());
    return static_cast<size_t>(result);
}

} // namespace std
