/**
 * Automatically generated by Zserio C++17 generator version 0.5.0 using Zserio core 2.17.0.
 * Generator setup: stdAllocator.
 */

#include <zserio/BitPositionUtil.h>
#include <zserio/BitStreamReader.h>
#include <zserio/BitStreamWriter.h>
#include <zserio/HashCodeUtil.h>

#include <struct_templated_field/StructTemplatedField.h>

namespace struct_templated_field
{
namespace StructTemplatedField
{

Data::Data() noexcept :
    Data(allocator_type{})
{
}

Data::Data(const allocator_type& allocator) noexcept :
        uint32Field(allocator),
        compoundField(allocator),
        stringField(allocator)
{
}

Data::Data(Data&& other, const allocator_type& allocator) :
        uint32Field(std::move(other.uint32Field), allocator),
        compoundField(std::move(other.compoundField), allocator),
        stringField(std::move(other.stringField), allocator)
{
}

Data::Data(const Data& other, const allocator_type& allocator) :
        uint32Field(other.uint32Field, allocator),
        compoundField(other.compoundField, allocator),
        stringField(other.stringField, allocator)
{
}

Data::Data(
        ::struct_templated_field::Field::Data<::zserio::UInt32> uint32Field_,
        ::struct_templated_field::Field::Data<::struct_templated_field::Compound::Data> compoundField_,
        ::struct_templated_field::Field::Data<::zserio::String> stringField_,
        const allocator_type& allocator) :
        uint32Field(::std::move(uint32Field_), allocator),
        compoundField(::std::move(compoundField_), allocator),
        stringField(::std::move(stringField_), allocator)
{
}

bool operator==(const Data& lhs, const Data& rhs)
{
    return ::std::tie(
            lhs.uint32Field,
            lhs.compoundField,
            lhs.stringField)
            == ::std::tie(
            rhs.uint32Field,
            rhs.compoundField,
            rhs.stringField);
}

bool operator<(const Data& lhs, const Data& rhs)
{
    return ::std::tie(
            lhs.uint32Field,
            lhs.compoundField,
            lhs.stringField)
            < ::std::tie(
            rhs.uint32Field,
            rhs.compoundField,
            rhs.stringField);
}

bool operator!=(const Data& lhs, const Data& rhs)
{
    return !(lhs == rhs);
}

bool operator>(const Data& lhs, const Data& rhs)
{
    return rhs < lhs;
}

bool operator<=(const Data& lhs, const Data& rhs)
{
    return !(rhs < lhs);
}

bool operator>=(const Data& lhs, const Data& rhs)
{
    return !(lhs < rhs);
}

} // namespace StructTemplatedField
} // namespace struct_templated_field

namespace zserio
{

View<::struct_templated_field::StructTemplatedField::Data>::View(const ::struct_templated_field::StructTemplatedField::Data& data) noexcept :
        m_data(&data)
{}

View<::struct_templated_field::StructTemplatedField::Data>::View(const ::struct_templated_field::StructTemplatedField::Data& data,
        const View&) noexcept :
        m_data(&data)
{}

::zserio::View<::struct_templated_field::Field::Data<::zserio::UInt32>> View<::struct_templated_field::StructTemplatedField::Data>::uint32Field() const
{
    return ::zserio::View<::struct_templated_field::Field::Data<::zserio::UInt32>>(m_data->uint32Field);
}

::zserio::View<::struct_templated_field::Field::Data<::struct_templated_field::Compound::Data>> View<::struct_templated_field::StructTemplatedField::Data>::compoundField() const
{
    return ::zserio::View<::struct_templated_field::Field::Data<::struct_templated_field::Compound::Data>>(m_data->compoundField);
}

::zserio::View<::struct_templated_field::Field::Data<::zserio::String>> View<::struct_templated_field::StructTemplatedField::Data>::stringField() const
{
    return ::zserio::View<::struct_templated_field::Field::Data<::zserio::String>>(m_data->stringField);
}

const ::struct_templated_field::StructTemplatedField::Data& View<::struct_templated_field::StructTemplatedField::Data>::zserioData() const
{
    return *m_data;
}

bool operator==(const View<::struct_templated_field::StructTemplatedField::Data>& lhs, const View<::struct_templated_field::StructTemplatedField::Data>& rhs)
{
    return lhs.uint32Field() == rhs.uint32Field() &&
            lhs.compoundField() == rhs.compoundField() &&
            lhs.stringField() == rhs.stringField();
}

bool operator<(const View<::struct_templated_field::StructTemplatedField::Data>& lhs, const View<::struct_templated_field::StructTemplatedField::Data>& rhs)
{
    if (lhs.uint32Field() != rhs.uint32Field())
    {
        return lhs.uint32Field() < rhs.uint32Field();
    }
    if (lhs.compoundField() != rhs.compoundField())
    {
        return lhs.compoundField() < rhs.compoundField();
    }
    if (lhs.stringField() != rhs.stringField())
    {
        return lhs.stringField() < rhs.stringField();
    }

    return false;
}

bool operator!=(const View<::struct_templated_field::StructTemplatedField::Data>& lhs, const View<::struct_templated_field::StructTemplatedField::Data>& rhs)
{
    return !(lhs == rhs);
}

bool operator>(const View<::struct_templated_field::StructTemplatedField::Data>& lhs, const View<::struct_templated_field::StructTemplatedField::Data>& rhs)
{
    return rhs < lhs;
}

bool operator<=(const View<::struct_templated_field::StructTemplatedField::Data>& lhs, const View<::struct_templated_field::StructTemplatedField::Data>& rhs)
{
    return !(rhs < lhs);
}

bool operator>=(const View<::struct_templated_field::StructTemplatedField::Data>& lhs, const View<::struct_templated_field::StructTemplatedField::Data>& rhs)
{
    return !(lhs < rhs);
}

namespace detail
{

void ObjectTraits<::struct_templated_field::StructTemplatedField::Data>::validate(const View<::struct_templated_field::StructTemplatedField::Data>& view, ::std::string_view)
{
    detail::validate(view.uint32Field(), "'StructTemplatedField.uint32Field'");
    detail::validate(view.compoundField(), "'StructTemplatedField.compoundField'");
    detail::validate(view.stringField(), "'StructTemplatedField.stringField'");
}

BitSize ObjectTraits<::struct_templated_field::StructTemplatedField::Data>::bitSizeOf(const View<::struct_templated_field::StructTemplatedField::Data>& view, BitSize bitPosition)
{
    BitSize endBitPosition = bitPosition;

    auto uint32Field_ = view.uint32Field();
    endBitPosition += detail::bitSizeOf(uint32Field_, endBitPosition);
    auto compoundField_ = view.compoundField();
    endBitPosition += detail::bitSizeOf(compoundField_, endBitPosition);
    auto stringField_ = view.stringField();
    endBitPosition += detail::bitSizeOf(stringField_, endBitPosition);

    return endBitPosition - bitPosition;
}

void ObjectTraits<::struct_templated_field::StructTemplatedField::Data>::write(BitStreamWriter& writer, const View<::struct_templated_field::StructTemplatedField::Data>& view)
{
    auto uint32Field_ = view.uint32Field();
    detail::write(writer, uint32Field_);
    auto compoundField_ = view.compoundField();
    detail::write(writer, compoundField_);
    auto stringField_ = view.stringField();
    detail::write(writer, stringField_);
}

View<::struct_templated_field::StructTemplatedField::Data> ObjectTraits<::struct_templated_field::StructTemplatedField::Data>::read(BitStreamReader& reader, ::struct_templated_field::StructTemplatedField::Data& data)
{
    View<::struct_templated_field::StructTemplatedField::Data> view(data);
    (void)detail::read(reader, data.uint32Field);
    (void)detail::read(reader, data.compoundField);
    (void)detail::read(reader, data.stringField);
    return view;
}

} // namespace detail
} // namespace zserio

namespace std
{

size_t hash<::struct_templated_field::StructTemplatedField::Data>::operator()(const ::struct_templated_field::StructTemplatedField::Data& data) const
{
    uint32_t result = ::zserio::HASH_SEED;
    result = ::zserio::calcHashCode(result, data.uint32Field);
    result = ::zserio::calcHashCode(result, data.compoundField);
    result = ::zserio::calcHashCode(result, data.stringField);
    return static_cast<size_t>(result);
}

size_t hash<::zserio::View<::struct_templated_field::StructTemplatedField::Data>>::operator()(const ::zserio::View<::struct_templated_field::StructTemplatedField::Data>& view) const
{
    uint32_t result = ::zserio::HASH_SEED;
    result = ::zserio::calcHashCode(result, view.uint32Field());
    result = ::zserio::calcHashCode(result, view.compoundField());
    result = ::zserio::calcHashCode(result, view.stringField());
    return static_cast<size_t>(result);
}

} // namespace std
